import time
print("Hi, i.am.pss")
print("I Tend To Forget Thing")
print("")
print("Especially, Lose Track Of  ")
print("")
print("//////////////////////////     //////////////////////////////        //                  //     ||///////////////////")
print("            //                              //                       ////              ////     ||")
print("            f//                              //                       // //            // //     ||")
print("            //                              //                       //  //          //  //     ||")
print("            //                              //                       //   //        //   //     ||")
print("            //                              //                       //    //      //    //     ||")
print("            //                              //                       //     //    //     //     ||//////////////////")
print("            //                              //                       //      //  //      //     ||  ")
print("            //                              //                       //        //        //     ||")
print("            //                              //                       //                  //     ||")
print("            //                              //                       //                  //     ||  ")
print("            //                              //                       //                  //     || ")
print("            //                  //////////////////////////////       //                  //     ||////////////////////")
print("")
print("Do You Do So?, Wait And Answer These Questions:")
print("")
print("What's Your Name: ")
name=str(input())
print(name, "What Shall I Remind You?:- ")
text=str(input())
print("In How Many Minutes?:- ")
local_time = float(input())
local_time = local_time*60
time.sleep(local_time)
print(name, "I'm Back, I Have Reminded You About: ", text)